### ISSUE TITLE
Documentation links to 404 page error

### ISSUE THREAD

**Issue by ndearns** [servo/rust-azure#306]
The Documentation link at the foot of the https://github.com/servo/rust-azure page produces a 404 error.

**Comment by jdm** [comment]
That's true. If the docs aren't on docs.rs, then there's not really anything we can do. This crate is no longer used or maintained by the Servo team; we rely on the `raqote` crate instead.

**Comment by jdm** [comment]
Looks like https://docs.rs/azure/ does exist.
